name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --fetch-timeout=60000

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier
        run: npm run format -- --check
        continue-on-error: true

      - name: Check for secrets
        run: git secrets --scan
        continue-on-error: true

      - name: Run SonarQube Analysis (optional)
        run: |
          echo "Running SonarQube analysis..."
        continue-on-error: true

      - name: Report status
        run: echo "Code analysis completed."
